# Generated by Django 5.0.1 on 2024-01-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
    ]
