# Generated by Django 5.0.1 on 2024-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=15)),
                ('body1', models.CharField(max_length=50)),
                ('heading2', models.CharField(max_length=15)),
                ('body2', models.CharField(max_length=50)),
                ('heading3', models.CharField(max_length=15)),
                ('body3', models.CharField(max_length=50)),
            ],
        ),
    ]
