# Generated by Django 5.0.1 on 2024-01-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0006_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('compname1', models.CharField(max_length=20)),
                ('compcontent1', models.CharField(max_length=40)),
                ('compname2', models.CharField(max_length=20)),
                ('compcontent2', models.CharField(max_length=40)),
            ],
        ),
    ]
