# Generated by Django 5.0.1 on 2024-01-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0009_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='static/bis/images/5856.jpg', upload_to='images/%y'),
        ),
    ]
