# Generated by Django 5.0.1 on 2024-02-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0010_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='static/bis/images/5856.jpg', upload_to='images/'),
        ),
    ]
