# Generated by Django 5.0.1 on 2024-02-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0011_career_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bis.career')),
            ],
        ),
    ]
