# Generated by Django 5.0.1 on 2024-02-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0012_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='requirements',
        ),
    ]
