# Generated by Django 5.0.1 on 2024-02-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0015_alter_goals_heading3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='services',
            name='heading',
            field=models.CharField(max_length=500),
        ),
    ]
