# Generated by Django 5.0.1 on 2024-02-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0016_alter_services_content_alter_services_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='additional_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
