# Generated by Django 5.0.1 on 2024-02-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0018_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='additional_text',
            field=models.TextField(blank=True),
        ),
    ]
