# Generated by Django 5.0.1 on 2024-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0020_remove_additional_additional_additional_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='compcontent3',
            field=models.CharField(default='hui', max_length=40),
        ),
        migrations.AddField(
            model_name='carousel',
            name='compcontent4',
            field=models.CharField(default='hui', max_length=40),
        ),
        migrations.AddField(
            model_name='carousel',
            name='compcontent5',
            field=models.CharField(default='hui', max_length=40),
        ),
        migrations.AddField(
            model_name='carousel',
            name='compname3',
            field=models.CharField(default='hui', max_length=20),
        ),
        migrations.AddField(
            model_name='carousel',
            name='compname4',
            field=models.CharField(default='hui', max_length=20),
        ),
        migrations.AddField(
            model_name='carousel',
            name='compname5',
            field=models.CharField(default='hui', max_length=20),
        ),
    ]
