# Generated by Django 5.0.1 on 2024-02-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0021_carousel_compcontent3_carousel_compcontent4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='compcontent1',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='compcontent2',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='compcontent3',
            field=models.CharField(default='hui', max_length=400),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='compcontent4',
            field=models.CharField(default='hui', max_length=400),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='compcontent5',
            field=models.CharField(default='hui', max_length=400),
        ),
    ]
